version: 0.2

phases:
  install:
    runtime-version:
      asgiref==3.5.2
      Django==4.1.3
      sqlparse==0.4.3
      tzdata==2022.7
     pre_build:
      commands:
        - echo Nothing to do in pre build ...
        
      build:
         commands:
          - echo Build started on `date`
      post_build:
         commands:
          - echo Build completed on `date`
          
       artifacts:
          files:
            - '**/*'
          
         
